"use client";

import "@/app/globals.css";
import Link from "next/link";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full bg-orange-600">
          <nav className="bg-orange-200 flex gap-3 text-orange-600 font-extrabold border-b-8 border-orange-600 text-2xl h-[--header-height]">
            <Link href="/"  className="ml-4 my-auto">
              <span>Dawn Pic</span>
            </Link>
          </nav>

          <main className="flex min-h-[calc(100vh-var(--header-height))]">
            {children}
          </main>

          <footer className="flex flex-row bg-orange-200 font-extrabold items-center h-[--footer-height] text-orange-500">
            <p className="ml-10">Copyright © 2024 Dawn Pic</p>
            <a href="https://raw.githubusercontent.com/hanyujie2002/DawnPic/main/LICENSE" className="ml-3 hover:underline">MIT Licence</a>
            <p className="ml-auto">Powered by</p>
            <a href="https://nextjs.org/" className="hover:underline ml-1 mr-4">Nuxt.js</a>
          </footer>
        </div>
      </body>
    </html>
  );
}
